#############################################################################
# Makefile for building: address-book
# Generated by qmake (2.01a) (Qt 4.6.2) on: Mon Mar 7 20:35:15 2011
# Project:  address-book.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile address-book.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Isrc -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = src/

####### Files

SOURCES       = src/addressbookcontroller.cpp \
		src/contact.cpp \
		src/contactdetailform.cpp \
		src/contactlist.cpp \
		src/dummydatasource.cpp \
		src/main.cpp \
		src/mainwindow.cpp moc_contactdetailform.cpp \
		moc_contactlist.cpp \
		moc_mainwindow.cpp
OBJECTS       = src/addressbookcontroller.o \
		src/contact.o \
		src/contactdetailform.o \
		src/contactlist.o \
		src/dummydatasource.o \
		src/main.o \
		src/mainwindow.o \
		src/moc_contactdetailform.o \
		src/moc_contactlist.o \
		src/moc_mainwindow.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		address-book.pro
QMAKE_TARGET  = address-book
DESTDIR       = 
TARGET        = address-book

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: address-book.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile address-book.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile address-book.pro

dist: 
	@$(CHK_DIR_EXISTS) src/address-book1.0.0 || $(MKDIR) src/address-book1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) src/address-book1.0.0/ && $(COPY_FILE) --parents src/addressbookcontroller.h src/contact.h src/contactdetailform.h src/contactlist.h src/datasource.h src/dummydatasource.h src/errorinfo.h src/mainwindow.h src/address-book1.0.0/ && $(COPY_FILE) --parents src/addressbookcontroller.cpp src/contact.cpp src/contactdetailform.cpp src/contactlist.cpp src/dummydatasource.cpp src/main.cpp src/mainwindow.cpp src/address-book1.0.0/ && (cd `dirname src/address-book1.0.0` && $(TAR) address-book1.0.0.tar address-book1.0.0 && $(COMPRESS) address-book1.0.0.tar) && $(MOVE) `dirname src/address-book1.0.0`/address-book1.0.0.tar.gz . && $(DEL_FILE) -r src/address-book1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_contactdetailform.cpp moc_contactlist.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_contactdetailform.cpp moc_contactlist.cpp moc_mainwindow.cpp
moc_contactdetailform.cpp: src/contact.h \
		src/addressbookcontroller.h \
		src/datasource.h \
		src/errorinfo.h \
		src/contactdetailform.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/contactdetailform.h -o moc_contactdetailform.cpp

moc_contactlist.cpp: src/addressbookcontroller.h \
		src/contact.h \
		src/datasource.h \
		src/errorinfo.h \
		src/contactlist.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/contactlist.h -o moc_contactlist.cpp

moc_mainwindow.cpp: src/addressbookcontroller.h \
		src/contact.h \
		src/datasource.h \
		src/errorinfo.h \
		src/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

src/addressbookcontroller.o: src/addressbookcontroller.cpp src/addressbookcontroller.h \
		src/contact.h \
		src/datasource.h \
		src/errorinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/addressbookcontroller.o src/addressbookcontroller.cpp

src/contact.o: src/contact.cpp src/contact.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/contact.o src/contact.cpp

src/contactdetailform.o: src/contactdetailform.cpp src/contactdetailform.h \
		src/contact.h \
		src/addressbookcontroller.h \
		src/datasource.h \
		src/errorinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/contactdetailform.o src/contactdetailform.cpp

src/contactlist.o: src/contactlist.cpp src/addressbookcontroller.h \
		src/contact.h \
		src/datasource.h \
		src/errorinfo.h \
		src/contactlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/contactlist.o src/contactlist.cpp

src/dummydatasource.o: src/dummydatasource.cpp src/dummydatasource.h \
		src/datasource.h \
		src/contact.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/dummydatasource.o src/dummydatasource.cpp

src/main.o: src/main.cpp src/addressbookcontroller.h \
		src/contact.h \
		src/datasource.h \
		src/errorinfo.h \
		src/dummydatasource.h \
		src/mainwindow.h \
		src/contactlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/main.o src/main.cpp

src/mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/addressbookcontroller.h \
		src/contact.h \
		src/datasource.h \
		src/errorinfo.h \
		src/contactlist.h \
		src/contactdetailform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/mainwindow.o src/mainwindow.cpp

src/moc_contactdetailform.o: moc_contactdetailform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/moc_contactdetailform.o moc_contactdetailform.cpp

src/moc_contactlist.o: moc_contactlist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/moc_contactlist.o moc_contactlist.cpp

src/moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

